spring:
  datasource:
    username: pix
    password: pix
    url: jdbc:mysql://localhost:3306/pix
    platform: mysql
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"