spring:
  datasource:
    username: pix
    password: pix
    url: jdbc:mysql://localhost:3306/pix
    platform: mysql
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"